<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 9pt; }
        .header { text-align: center; margin-bottom: 20px; }
        .institution-name { font-size: 14pt; font-weight: bold; text-transform: uppercase; }
        .report-title { font-size: 12pt; font-weight: bold; margin-top: 5px; }
        .meta { font-size: 8pt; color: #555; margin-bottom: 10px; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .risk-badges span { display: inline-block; padding: 2px 4px; border-radius: 3px; font-size: 8pt; margin-right: 3px; background: #fee2e2; color: #991b1b; }
    </style>
</head>
<body>
    <div class="header">
        <div class="institution-name">Kigamboni City College of Health and Allied Sciences (KIBIHAS)</div>
        <div class="report-title">{{ $title }}</div>
    </div>

    <div class="meta">
        <strong>Generated On:</strong> {{ now()->format('d M Y H:i') }} | 
        <strong>Generated By:</strong> {{ auth()->user()->name }} |
        <strong>Filters:</strong> 
        @if(!empty($filters['academic_year_id'])) AY {{ $filters['academic_year_id'] }} @endif
        @if(!empty($filters['semester_id'])) Sem {{ $filters['semester_id'] }} @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Reg No</th>
                <th>Name</th>
                <th>Programme</th>
                <th>Level</th>
                <th>GPA</th>
                <th>Fails</th>
                <th>Risk Factors</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $student)
                <tr>
                    <td>{{ $student['registration_number'] }}</td>
                    <td>{{ $student['name'] }}</td>
                    <td>{{ $student['program_code'] }}</td>
                    <td>{{ $student['nta_level'] }}</td>
                    <td>{{ $student['gpa'] }}</td>
                    <td>{{ $student['fails'] }}</td>
                    <td class="risk-badges">
                        @foreach($student['reasons'] as $reason)
                            <span>{{ $reason }}</span>
                        @endforeach
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; padding: 20px;">No at-risk students found matching criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
