<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10pt; line-height: 1.4; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .institution-name { font-size: 16pt; font-weight: bold; margin-bottom: 5px; text-transform: uppercase; }
        .report-title { font-size: 14pt; font-weight: bold; margin-bottom: 5px; }
        .meta-info { font-size: 8pt; color: #666; text-align: right; margin-bottom: 15px; }
        
        .student-info { margin-bottom: 20px; width: 100%; border-collapse: collapse; }
        .student-info td { padding: 5px; vertical-align: top; }
        .label { font-weight: bold; color: #555; width: 150px; }
        
        .results-section { margin-top: 20px; }
        .period-header { background-color: #f0f0f0; padding: 5px 10px; font-weight: bold; border-bottom: 1px solid #ccc; margin-top: 15px; }
        
        table.results-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        table.results-table th, table.results-table td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 9pt; }
        table.results-table th { background-color: #f8f9fa; font-weight: bold; text-align: center; }
        table.results-table td.center { text-align: center; }
        table.results-table td.right { text-align: right; }
        
        .summary-row { background-color: #f9f9f9; font-weight: bold; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 8pt; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 5px; }
        .page-number:after { content: counter(page); }
        
        .status-pass { color: green; font-weight: bold; }
        .status-fail { color: red; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="institution-name">Kigamboni City College of Health and Allied Sciences (KIBIHAS)</div>
        <div class="report-title">Official Statement of Results</div>
    </div>

    <div class="meta-info">
        Generated by: {{ auth()->user()->name }} | Generated on: {{ now()->format('d M Y H:i') }}
    </div>

    <table class="student-info">
        <tr>
            <td class="label">Student Name:</td>
            <td>{{ $data['student']->user->name }}</td>
            <td class="label">Registration No:</td>
            <td>{{ $data['student']->registration_number }}</td>
        </tr>
        <tr>
            <td class="label">NACTVET Reg No:</td>
            <td>{{ $data['student']->nactvet_registration_number ?? 'N/A' }}</td>
            <td class="label">Programme:</td>
            <td>{{ $data['student']->program->name }} ({{ $data['student']->program->code }})</td>
        </tr>
        <tr>
            <td class="label">Current Level:</td>
            <td>NTA Level {{ $data['student']->current_nta_level }}</td>
            <td class="label">Intake Year:</td>
            <td>{{ $data['student']->created_at->format('Y') }}</td>
        </tr>
        <tr>
            <td class="label">Status:</td>
            <td>{{ ucfirst($data['student']->status) }}</td>
            <td class="label"></td>
            <td></td>
        </tr>
    </table>

    <div class="results-section">
        @forelse($data['results'] as $period => $periodResults)
            <div class="period-header">{{ $period }}</div>
            <table class="results-table">
                <thead>
                    <tr>
                        <th style="width: 15%;">Code</th>
                        <th style="width: 45%;">Module Name</th>
                        <th style="width: 10%;">Credits</th>
                        <th style="width: 10%;">Grade</th>
                        <th style="width: 10%;">Point</th>
                        <th style="width: 10%;">Remark</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $periodPoints = 0;
                        $periodCredits = 0;
                    @endphp
                    @foreach($periodResults as $result)
                        @php
                            if($result->grade_point !== null && $result->credits_snapshot > 0) {
                                $periodPoints += $result->grade_point * $result->credits_snapshot;
                                $periodCredits += $result->credits_snapshot;
                            }
                        @endphp
                        <tr>
                            <td>{{ $result->moduleOffering->module->code }}</td>
                            <td>{{ $result->moduleOffering->module->name }}</td>
                            <td class="center">{{ $result->credits_snapshot }}</td>
                            <td class="center font-bold">{{ $result->grade ?? '-' }}</td>
                            <td class="center">{{ $result->grade_point ?? '-' }}</td>
                            <td class="center">
                                <span class="{{ $result->total_mark >= 40 ? 'status-pass' : 'status-fail' }}">
                                    {{ $result->total_mark >= 40 ? 'PASS' : 'FAIL' }}
                                </span>
                            </td>
                        </tr>
                    @endforeach
                    <tr class="summary-row">
                        <td colspan="4" class="right">Semester GPA:</td>
                        <td colspan="2" class="center">
                            @if($periodCredits > 0)
                                {{ number_format($periodPoints / $periodCredits, 2) }}
                            @else
                                -
                            @endif
                        </td>
                    </tr>
                </tbody>
            </table>
        @empty
            <div style="padding: 20px; text-align: center; color: #666; font-style: italic;">
                No published results available for this student.
            </div>
        @endforelse
    </div>

    <div class="footer">
        Page <span class="page-number"></span> | This document is an official academic record of KIBIHAS.
    </div>
</body>
</html>
