<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Academic Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .logo {
            width: 80px;
            height: auto;
            margin-bottom: 5px;
        }
        .institution-name {
            font-size: 16pt;
            font-weight: bold;
            text-transform: uppercase;
            margin: 0;
        }
        .report-title {
            font-size: 14pt;
            font-weight: bold;
            margin: 5px 0;
        }
        .meta-info {
            font-size: 9pt;
            color: #666;
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8pt;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
        .page-number:after {
            content: counter(page);
        }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .badge {
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 8pt;
        }
        .badge-success { background-color: #d1fae5; color: #065f46; }
        .badge-warning { background-color: #fef3c7; color: #92400e; }
        .badge-danger { background-color: #fee2e2; color: #b91c1c; }
    </style>
</head>
<body>
    <div class="header">
        <!-- <img src="{{ public_path('images/logo.png') }}" class="logo" alt="Logo"> -->
        <h1 class="institution-name">Kigamboni City College of Health and Allied Sciences (KIBIHAS)</h1>
        <div class="report-title">@yield('title')</div>
        <div class="meta-info">
            Academic Year: {{ $filters['academic_year_name'] ?? 'All' }} | 
            Semester: {{ $filters['semester_name'] ?? 'All' }}
        </div>
    </div>

    <div class="content">
        @yield('content')
    </div>

    <div class="footer">
        Generated by {{ auth()->user()->name }} on {{ now()->format('d M Y, H:i') }} | Page <span class="page-number"></span>
    </div>
</body>
</html>
