<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Delivery Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            margin-bottom: 20px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 10px;
        }
        .title {
            font-size: 18px;
            font-weight: bold;
            color: #000;
        }
        .meta {
            margin-top: 5px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .status-read {
            color: green;
            font-weight: bold;
        }
        .status-pending {
            color: #e6a800;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Delivery Report</div>
        <div class="meta">
            <strong>Subject:</strong> {{ $type === 'message' ? $item->subject : $item->title }}<br>
            <strong>Date:</strong> {{ $item->created_at->format('d M Y, H:i') }}<br>
            <strong>Type:</strong> {{ ucfirst($type) }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Recipient Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Read At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($recipients as $row)
                @php
                    $user = $type === 'message' ? $row->recipient : $row->user;
                    $readAt = $row->read_at;
                @endphp
                <tr>
                    <td>{{ $user->name ?? 'Unknown' }}</td>
                    <td>{{ $user->email ?? 'N/A' }}</td>
                    <td>{{ $user->getRoleNames()->first() ?? '-' }}</td>
                    <td>
                        @if($readAt)
                            <span class="status-read">Read</span>
                        @else
                            <span class="status-pending">Pending</span>
                        @endif
                    </td>
                    <td>{{ $readAt ? $readAt->format('d M Y, H:i') : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 30px; font-size: 10px; color: #999; text-align: center;">
        Generated by KIBIHAS System on {{ now()->format('d M Y, H:i') }}
    </div>
</body>
</html>
